apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deploy
  labels:
    app: flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec: 
      containers:
      - image: lyzhang1999/hello-world-flask:latest
        name: hello-world-flask
    